# Generated by Django 4.2.6 on 2023-12-02 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('viewed', models.IntegerField(blank=True, default=0, null=True)),
                ('correct_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('wrong_answers', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deck')),
            ],
        ),
    ]
