# Generated by Django 4.2.6 on 2023-12-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLanguage',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
