# Generated by Django 4.2.6 on 2024-01-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_availablelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableLanguage',
        ),
    ]
