# Generated by Django 4.2.6 on 2024-01-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_availablecourse_delete_availablelanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_xp', models.IntegerField(blank=True, default=0, null=True)),
                ('monthly_xp', models.IntegerField(blank=True, default=0, null=True)),
                ('total_xp', models.IntegerField(blank=True, default=0, null=True)),
                ('last_reviewed_language_code', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
