# Generated by Django 4.2.6 on 2024-01-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userloginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='last_reviewed_language_code',
            field=models.CharField(default='gb', max_length=5),
        ),
    ]
